USE [master]
GO

/****** Object:  Database [BD_BANCO1]    Script Date: 23/02/2024 18:47:59 ******/
CREATE DATABASE [BD_BANCO1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_BANCO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLSERVER2016\MSSQL\DATA\BD_BANCO1.mdf' , SIZE = 125952KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BD_BANCO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLSERVER2016\MSSQL\DATA\BD_BANCO1_0.ldf' , SIZE = 43264KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_BANCO1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_BANCO1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_BANCO1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_BANCO1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_BANCO1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_BANCO1] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_BANCO1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BD_BANCO1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_BANCO1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_BANCO1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_BANCO1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_BANCO1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_BANCO1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_BANCO1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_BANCO1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_BANCO1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BD_BANCO1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_BANCO1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_BANCO1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_BANCO1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_BANCO1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_BANCO1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_BANCO1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_BANCO1] SET RECOVERY FULL 
GO

ALTER DATABASE [BD_BANCO1] SET  MULTI_USER 
GO

ALTER DATABASE [BD_BANCO1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_BANCO1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD_BANCO1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD_BANCO1] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BD_BANCO1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BD_BANCO1] SET QUERY_STORE = OFF
GO

USE [BD_BANCO1]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [BD_BANCO1] SET  READ_WRITE 
GO

