---------------------HACER UN TABLA DONDE SE ANALICE LA CANTIDAD DE ALTAS EN EL AÑO 2000----------------
-----------------------------AGRUPADAS POR AREA Y DEPARTAMENTO------------------------------------------

--------------------------------------------USANDO ROLLUP-----------------------------------------------

--Tablas involucradas
SELECT * FROM [dbo].[TB_CLIENTE_PERFIL]

SELECT * FROM [dbo].[TB_UBIGEO]

--Tabla resultante del join para a analizar
SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE YEAR(A.FH_ALTA) = 2000
GROUP BY YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO
ORDER BY YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO

--Tabla resultante del ROLLUP
SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE YEAR(A.FH_ALTA) = 2000
GROUP BY ROLLUP(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO)
ORDER BY YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO

--Mostar los resultado cada uno de manera independiente, cantidad de altas en el año 2000
SELECT * FROM (
		SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
		FROM [dbo].[TB_CLIENTE_PERFIL] A
		INNER JOIN [dbo].[TB_UBIGEO] B
		ON A.COD_UBIGEO = B.COD_UBIGEO
		WHERE YEAR(A.FH_ALTA) = 2000
		GROUP BY ROLLUP(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO)
) T
WHERE AÑO_ALTA IS NOT NULL AND
	AREA IS NULL AND
	DEPARTAMENTO IS NULL

--Mostar los resultado cada uno de manera independiente, cantidad de altas en el año 2000 por area
SELECT * FROM (
		SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
		FROM [dbo].[TB_CLIENTE_PERFIL] A
		INNER JOIN [dbo].[TB_UBIGEO] B
		ON A.COD_UBIGEO = B.COD_UBIGEO
		WHERE YEAR(A.FH_ALTA) = 2000
		GROUP BY ROLLUP(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO)
) T
WHERE AÑO_ALTA IS NOT NULL AND
	AREA IS NOT NULL AND
	DEPARTAMENTO IS NULL

--Mostar los resultado cada uno de manera independiente, cantidad de altas en el año 2000 por area y departamento
SELECT * FROM (
		SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
		FROM [dbo].[TB_CLIENTE_PERFIL] A
		INNER JOIN [dbo].[TB_UBIGEO] B
		ON A.COD_UBIGEO = B.COD_UBIGEO
		WHERE YEAR(A.FH_ALTA) = 2000
		GROUP BY ROLLUP(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO)
) T
WHERE AÑO_ALTA IS NOT NULL AND
	AREA IS NOT NULL AND
	DEPARTAMENTO IS NOT NULL

--------------------------------------------USANDO CUBE-----------------------------------------------

--Tabla resultante del CUBE
SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE YEAR(A.FH_ALTA) = 2000
GROUP BY CUBE(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO)
ORDER BY YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO

--Mostar los resultado cada uno de manera independiente, cantidad de altas en el año 2000
SELECT * FROM (
		SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
		FROM [dbo].[TB_CLIENTE_PERFIL] A
		INNER JOIN [dbo].[TB_UBIGEO] B
		ON A.COD_UBIGEO = B.COD_UBIGEO
		WHERE YEAR(A.FH_ALTA) = 2000
		GROUP BY CUBE(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO)
) T
WHERE AÑO_ALTA IS NOT NULL AND
	AREA IS NULL AND
	DEPARTAMENTO IS NULL

--Mostar los resultado cada uno de manera independiente, cantidad de altas por area
SELECT * FROM (
		SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
		FROM [dbo].[TB_CLIENTE_PERFIL] A
		INNER JOIN [dbo].[TB_UBIGEO] B
		ON A.COD_UBIGEO = B.COD_UBIGEO
		WHERE YEAR(A.FH_ALTA) = 2000
		GROUP BY CUBE(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO)
) T
WHERE AÑO_ALTA IS NULL AND
	AREA IS NOT NULL AND
	DEPARTAMENTO IS NULL

--Mostar los resultado cada uno de manera independiente, cantidad de altas por departamento
SELECT * FROM (
		SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
		FROM [dbo].[TB_CLIENTE_PERFIL] A
		INNER JOIN [dbo].[TB_UBIGEO] B
		ON A.COD_UBIGEO = B.COD_UBIGEO
		WHERE YEAR(A.FH_ALTA) = 2000
		GROUP BY CUBE(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO)
) T
WHERE AÑO_ALTA IS NULL AND
	AREA IS NULL AND
	DEPARTAMENTO IS NOT NULL

--Mostar los resultado cada uno de manera independiente, cantidad de altas por area en el año 2000
SELECT * FROM (
		SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
		FROM [dbo].[TB_CLIENTE_PERFIL] A
		INNER JOIN [dbo].[TB_UBIGEO] B
		ON A.COD_UBIGEO = B.COD_UBIGEO
		WHERE YEAR(A.FH_ALTA) = 2000
		GROUP BY CUBE(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO)
) T
WHERE AÑO_ALTA IS NOT NULL AND
	AREA IS NOT NULL AND
	DEPARTAMENTO IS NULL

--Mostar los resultado cada uno de manera independiente, cantidad de altas por departamento en el año 2000
SELECT * FROM (
		SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
		FROM [dbo].[TB_CLIENTE_PERFIL] A
		INNER JOIN [dbo].[TB_UBIGEO] B
		ON A.COD_UBIGEO = B.COD_UBIGEO
		WHERE YEAR(A.FH_ALTA) = 2000
		GROUP BY CUBE(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO)
) T
WHERE AÑO_ALTA IS NOT NULL AND
	AREA IS NULL AND
	DEPARTAMENTO IS NOT NULL

--Mostar los resultado cada uno de manera independiente, cantidad de altas por departamento y area
SELECT * FROM (
		SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
		FROM [dbo].[TB_CLIENTE_PERFIL] A
		INNER JOIN [dbo].[TB_UBIGEO] B
		ON A.COD_UBIGEO = B.COD_UBIGEO
		WHERE YEAR(A.FH_ALTA) = 2000
		GROUP BY CUBE(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO)
) T
WHERE AÑO_ALTA IS NULL AND
	AREA IS NOT NULL AND
	DEPARTAMENTO IS NOT NULL

--Mostar los resultado cada uno de manera independiente, cantidad de altas por departamento y area en el 2000
SELECT * FROM (
		SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
		FROM [dbo].[TB_CLIENTE_PERFIL] A
		INNER JOIN [dbo].[TB_UBIGEO] B
		ON A.COD_UBIGEO = B.COD_UBIGEO
		WHERE YEAR(A.FH_ALTA) = 2000
		GROUP BY CUBE(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO)
) T
WHERE AÑO_ALTA IS NOT NULL AND
	AREA IS NOT NULL AND
	DEPARTAMENTO IS NOT NULL

--------------------------------------USANDO GROUPING SET-----------------------------------------------

--Tabla resultante del GROUPING SET, agrupando por año, siempre se muestra el grupo base
SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE YEAR(A.FH_ALTA) = 2000
GROUP BY GROUPING SETS(
						(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO),
						(YEAR(A.FH_ALTA))
						)
ORDER BY YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO

--Tabla resultante del GROUPING SET, agrupando por area, siempre se muestra el grupo base
SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE YEAR(A.FH_ALTA) = 2000
GROUP BY GROUPING SETS(
						(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO),
						(B.AREA)
						)
ORDER BY YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO

--Tabla resultante del GROUPING SET, agrupando por departamento, siempre se muestra el grupo base
SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE YEAR(A.FH_ALTA) = 2000
GROUP BY GROUPING SETS(
						(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO),
						(B.DEPARTAMENTO)
						)
ORDER BY YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO

--Tabla resultante del GROUPING SET, agrupando por año y por area, siempre se muestra el grupo base
SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE YEAR(A.FH_ALTA) = 2000
GROUP BY GROUPING SETS(
						(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO),
						(YEAR(A.FH_ALTA)),
						(B.AREA)
						)
ORDER BY YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO

--Tabla resultante del GROUPING SET, agrupando por año y por departamento, siempre se muestra el grupo base
SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA, B.DEPARTAMENTO,COUNT(A.CODIGO) CANTIDAD_ALTAS 
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE YEAR(A.FH_ALTA) = 2000
GROUP BY GROUPING SETS(
						(YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO),
						(YEAR(A.FH_ALTA)),
						(B.DEPARTAMENTO)
						)
ORDER BY YEAR(A.FH_ALTA), B.AREA, B.DEPARTAMENTO