-----------------------------------------STORED PROCEDURE-------------------------------------------------------

--Crear un procedimiento que muestre los clientes de lima centro con ingresos mayores a 3500-------
--y que tengas más de 10 cuentas-----

--Tablas a tomar en cuenta
SELECT * FROM [dbo].[TB_CLIENTE_PERFIL]
SELECT * FROM [dbo].[TB_CLIENTE_PRODUCTOS]
SELECT * FROM [dbo].[TB_AGENCIA]

--Creacion del procedure
CREATE PROCEDURE SP_CLIENTES10PRODUCTOS AS
BEGIN

SELECT A.CODIGO,A.INGRESO, 
		(B.CTA_AHORRO+B.CTA_CTS+B.CTA_FONDO+B.CTA_HIPOTECARIO+B.CTA_PLAZO+B.CTA_PRESTAMO+B.CTA_TARJETA) CUENTAS 
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_CLIENTE_PRODUCTOS] B 
ON A.CODIGO = B.CODIGO	
INNER JOIN [dbo].[TB_AGENCIA] C
ON A.COD_AGENCIA = C.COD_AGENCIA COLLATE Modern_Spanish_CI_AS
WHERE A.INGRESO > 35000 AND
	(B.CTA_AHORRO+B.CTA_CTS+B.CTA_FONDO+B.CTA_HIPOTECARIO+B.CTA_PLAZO+B.CTA_PRESTAMO+B.CTA_TARJETA) > 10 AND
	C.ZONA = 'LIMA CENTRO'
ORDER BY 2

END

--Ejecutando el procedure creado
EXEC [dbo].[SP_CLIENTES10PRODUCTOS]

--Creando el mismo procedure con parámetro de entrada
CREATE PROCEDURE SP_CLIENTES10PRODUCTOS_CONPA(@ZONA VARCHAR(255)) AS
BEGIN

SELECT A.CODIGO,A.INGRESO, 
		(B.CTA_AHORRO+B.CTA_CTS+B.CTA_FONDO+B.CTA_HIPOTECARIO+B.CTA_PLAZO+B.CTA_PRESTAMO+B.CTA_TARJETA) CUENTAS,
		C.ZONA
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_CLIENTE_PRODUCTOS] B 
ON A.CODIGO = B.CODIGO	
INNER JOIN [dbo].[TB_AGENCIA] C
ON A.COD_AGENCIA = C.COD_AGENCIA COLLATE Modern_Spanish_CI_AS
WHERE A.INGRESO > 35000 AND
	(B.CTA_AHORRO+B.CTA_CTS+B.CTA_FONDO+B.CTA_HIPOTECARIO+B.CTA_PLAZO+B.CTA_PRESTAMO+B.CTA_TARJETA) > 10 AND
	C.ZONA = @ZONA
ORDER BY 2

END

--Ejecutando el procedure con parametro de entrada
EXEC [dbo].[SP_CLIENTES10PRODUCTOS_CONPA] @ZONA = 'LIMA CENTRO'

--Clientes del departamento de Lima que tienen prestamo hipotecario y que tienen un saldo mayor a 200000----

--Tablas a tomar en cuenta
SELECT * FROM [dbo].[TB_CLIENTE_PERFIL]
SELECT * FROM [dbo].[TB_CLIENTE_PRESTAMOS]
SELECT * FROM [dbo].[TB_UBIGEO]

--Creacion del procedure
CREATE PROCEDURE SP_CLIENTESHIPO AS
BEGIN

SELECT A.CODIGO,B.SALDO_REAL,C.DEPARTAMENTO FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_CLIENTE_PRESTAMOS] B
ON A.CODIGO = B.CODIGO
INNER JOIN [dbo].[TB_UBIGEO] C
ON A.COD_UBIGEO = C.COD_UBIGEO
WHERE C.DEPARTAMENTO = 'LIMA' AND
	B.COD_PRODUCTO LIKE 'H%' AND
	B.SALDO_REAL > 500000
ORDER BY 2

END

--Ejecutando el procedure creado
EXEC [dbo].[SP_CLIENTESHIPO]

--Creando el mismo procedure con parámetro de entrada
ALTER PROCEDURE SP_CLIENTESHIPO_COMPA(@DEPARTAMENTO NVARCHAR(30)) AS
BEGIN

SELECT A.CODIGO,B.SALDO_REAL,B.COD_PRODUCTO,C.DEPARTAMENTO FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_CLIENTE_PRESTAMOS] B
ON A.CODIGO = B.CODIGO
INNER JOIN [dbo].[TB_UBIGEO] C
ON A.COD_UBIGEO = C.COD_UBIGEO
WHERE C.DEPARTAMENTO = @DEPARTAMENTO AND
	B.COD_PRODUCTO LIKE 'H%' AND
	B.SALDO_REAL > 500000
ORDER BY 2

END

--Ejecutando el procedure con parametro de entrada
EXEC [dbo].[SP_CLIENTESHIPO_COMPA] @DEPARTAMENTO = 'LIMA'

--Cliente del departamento de Lima que sean del sexo masculino, que tengan ingresos mayores a 35000----

--Tablas a tomar en cuenta
SELECT * FROM [dbo].[TB_CLIENTE_PERFIL]
SELECT * FROM [dbo].[TB_UBIGEO]

--Creacion del procedure
CREATE PROCEDURE SP_CLIENTEMLIMA AS
BEGIN

SELECT A.CODIGO,A.SEXO,A.INGRESO,B.DEPARTAMENTO 
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE B.DEPARTAMENTO = 'LIMA' AND
	A.SEXO = 'M' AND
	A.INGRESO > 35000
ORDER BY 3

END

--Ejecutando el procedure creado
EXEC [dbo].[SP_CLIENTEMLIMA]

--Creando el mismo procedure con parámetro de entrada
CREATE PROCEDURE SP_CLIENTEMLIMA_COMPA(@DEPARTAMENTO NVARCHAR(30), @SEXO NVARCHAR(1)) AS
BEGIN

SELECT A.CODIGO,A.SEXO,A.INGRESO,B.DEPARTAMENTO 
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE B.DEPARTAMENTO = @DEPARTAMENTO AND
	A.SEXO = @SEXO AND
	A.INGRESO > 35000
ORDER BY 3

END

--Ejecutando el procedure con parametro de entrada
EXEC [dbo].[SP_CLIENTEMLIMA_COMPA] @DEPARTAMENTO = 'LIMA', @SEXO = 'M'

----------------------------------------VISTAS------------------------------------------------

--Crear una vista donde se muestre datos de los clientes---

--Creacion de la vista
CREATE VIEW VW_DATOS AS
SELECT A.CODIGO,B.ZONA,A.SEXO,A.ECIVIL,C.DEPARTAMENTO, A.INGRESO 
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_AGENCIA] B
ON B.COD_AGENCIA = A.COD_AGENCIA COLLATE SQL_Latin1_General_CP1_CI_AS
INNER JOIN [dbo].[TB_UBIGEO] C
ON A.COD_UBIGEO = C.COD_UBIGEO
WHERE A.INGRESO IS NOT NULL AND A.INGRESO > 0

--Ejecutar vista
SELECT * FROM [dbo].[VW_DATOS]

--Mostrar los clientes con mayor desembolso en sus prestamos, mayor a 2 millones--

--Creacion de la vista
CREATE VIEW VW_CLIENTESMYPRES AS
SELECT TOP(4) DESEMBOLSO, CODIGO, COD_PRODUCTO FROM [dbo].[TB_CLIENTE_PRESTAMOS]
ORDER BY DESEMBOLSO DESC

--Mostrar vista
SELECT * FROM [dbo].[VW_CLIENTESMYPRES]

--Mostrar los clientes con mayores ingresos, mayor a 200 mil--

--Creacion de vista
CREATE VIEW VW_CLIENTESMYINGRE AS
SELECT TOP(4) INGRESO,CODIGO FROM [dbo].[TB_CLIENTE_PERFIL]
ORDER BY INGRESO DESC

--Mostrar vista
SELECT * FROM [dbo].[VW_CLIENTESMYINGRE]

-----------------------------------------FUNCIONES-----------------------------------------------

--Crear un tabla donde se muestre los datos de los clientes con desembolso mayor a 2 millones--
--y que sean de tipo prestamo empresas--

--Creacion de funcion
CREATE FUNCTION FN_CLIENTDESEM() RETURNS TABLE AS
RETURN 
(SELECT A.CODIGO, A.DESEMBOLSO,B.PRESTAMO FROM [dbo].[TB_CLIENTE_PRESTAMOS] A
INNER JOIN [dbo].[TB_TIPO_PRESTAMO] B
ON A.COD_PRODUCTO = B.COD_PRODUCTO
WHERE A.DESEMBOLSO > 2000000 AND 
B.PRESTAMO = 'PRESTAMO  EMPRESAS')

--Mostrar funcion 
SELECT * FROM [dbo].[FN_CLIENTDESEM]()

--Creacion de funcion con parametro
CREATE FUNCTION FN_CLIENTDESEM_COMPA(@PRESTAMO NVARCHAR(255)) RETURNS TABLE AS
RETURN 
(SELECT A.CODIGO, A.DESEMBOLSO,B.PRESTAMO FROM [dbo].[TB_CLIENTE_PRESTAMOS] A
INNER JOIN [dbo].[TB_TIPO_PRESTAMO] B
ON A.COD_PRODUCTO = B.COD_PRODUCTO
WHERE A.DESEMBOLSO > 2000000 AND 
B.PRESTAMO = @PRESTAMO)

--Mostrar funcion con parametro 
SELECT * FROM [dbo].[FN_CLIENTDESEM_COMPA]('PRESTAMO  EMPRESAS')

--Crear una tabla donde se muestes los datos de los clientes con ingresos mayores a 35000---
--que sean del departamento de lima---

--Creacion de funcion
CREATE FUNCTION FN_CLIENTEMYINGRE() RETURNS TABLE AS
RETURN
(SELECT A.CODIGO,A.INGRESO,B.DEPARTAMENTO FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE B.DEPARTAMENTO = 'LIMA' AND
	A.INGRESO > 35000)

--Mostrar funcion
SELECT * FROM [dbo].[FN_CLIENTEMYINGRE]()

--Creacion de funcion con parametro
CREATE FUNCTION FN_CLIENTEMYINGRE_COMPA(@DEPARTAMENTO NVARCHAR(30)) RETURNS TABLE AS
RETURN
(SELECT A.CODIGO,A.INGRESO,B.DEPARTAMENTO FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE B.DEPARTAMENTO = @DEPARTAMENTO AND
	A.INGRESO > 35000)

--Mostrar funcion con parametro
SELECT * FROM [dbo].[FN_CLIENTEMYINGRE_COMPA]('LIMA')

--Mostra la suma de desembolsos por cliente--
CREATE FUNCTION FN_SUMADESEM(@CODIGO NVARCHAR(12)) RETURNS FLOAT AS
BEGIN
	DECLARE @SUMA FLOAT
	SET @SUMA = (SELECT SUM(DESEMBOLSO) FROM [dbo].[TB_CLIENTE_PRESTAMOS]
	WHERE CODIGO = @CODIGO)
	RETURN @SUMA
END

--Mostrar la funcion

SELECT [dbo].[FN_SUMADESEM]('269219224584') SUMA_DESEMBOLSOS

