---------------HACER UNA TABLA DONDE SE ANALICE LA CANTIDAD DE DESEMBOLSO POR CADA MES DEL AÑO 2010-------------
----------------------------------AGRUPADA POR TIPO DE PRESTAMO-------------------------------------------------

--Tablas involucradas
SELECT * FROM [dbo].[TB_CLIENTE_PRESTAMOS]

SELECT * FROM [dbo].[TB_TIPO_PRESTAMO]

--Tabla resultate del Join que muestra los datos a pivotear
SELECT MONTH(A.FECHA_ALTA) MES_2010, B.PRESTAMO, SUM(A.DESEMBOLSO) DESEMBOLSO 
FROM [dbo].[TB_CLIENTE_PRESTAMOS] A
INNER JOIN [dbo].[TB_TIPO_PRESTAMO] B
ON A.COD_PRODUCTO = B.COD_PRODUCTO
WHERE YEAR(A.FECHA_ALTA) = 2010
GROUP BY MONTH(A.FECHA_ALTA), B.PRESTAMO
ORDER BY MONTH(A.FECHA_ALTA), B.PRESTAMO

--Tabla resultante del Pivot
SELECT PRESTAMO,
	[1] AS ENE_10,[2] AS FEB_10,[3] AS MAR_10,[4] AS ABR_10,[5] AS MAY_10,[6] AS JUN_10,
	[7] AS JUL_10,[8] AS AGO_10,[9] AS SET_10,[10] AS OCT10,[11] AS NOV_10,[12] AS DIC_10
	INTO TCREAD_PIVOT_PRESTAMOS2010
	FROM (
			SELECT MONTH(A.FECHA_ALTA) MES_2010, B.PRESTAMO, SUM(A.DESEMBOLSO) DESEMBOLSO 
			FROM [dbo].[TB_CLIENTE_PRESTAMOS] A
			INNER JOIN [dbo].[TB_TIPO_PRESTAMO] B
			ON A.COD_PRODUCTO = B.COD_PRODUCTO
			WHERE YEAR(A.FECHA_ALTA) = 2010
			GROUP BY MONTH(A.FECHA_ALTA), B.PRESTAMO
		) T
	PIVOT
		(
		SUM(DESEMBOLSO)
		FOR
		MES_2010 IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12]) 
		) AS PV
	ORDER BY PRESTAMO ASC

--Mostrando tabla Pivoteada
SELECT * FROM [dbo].[TCREAD_PIVOT_PRESTAMOS2010]

--Tabla resultante del UnPivot, regresando a la tabla inicial antes de pivotear
SELECT MES_2010, PRESTAMO, DESEMBOLSO 
INTO TCREADA_UNPIVOT_PRESTAMOS2010
FROM [dbo].[TCREAD_PIVOT_PRESTAMOS2010] T
UNPIVOT
	(
		DESEMBOLSO 
		FOR MES_2010 IN(ENE_10,FEB_10,MAR_10,ABR_10,MAY_10,JUN_10,
						JUL_10,AGO_10,SET_10,OCT10,NOV_10,DIC_10)
	) AS unpvt

--Mostrando tabla UnPivoteada
SELECT * FROM [dbo].[TCREADA_UNPIVOT_PRESTAMOS2010]

---------------------HACER UN TABLA DONDE SE ANALICE LA CANTIDAD DE ALTAS A PARTIR DEL AÑO 2000----------------
---------------------------------------------AGRUPADAS POR AREA------------------------------------------------

--Tablas involucradas
SELECT * FROM [dbo].[TB_CLIENTE_PERFIL]

SELECT * FROM [dbo].[TB_UBIGEO]

--Tabla resultate del Join que muestra los datos a pivotear
SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA,COUNT(A.CODIGO) CANTIDAD_ALTAS 
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE YEAR(A.FH_ALTA) >= 2000
GROUP BY YEAR(A.FH_ALTA), B.AREA
ORDER BY YEAR(A.FH_ALTA), B.AREA

--Tabla resultante del Pivot
SELECT AREA,
	[2000] AS Año2000,[2001] AS Año2001,[2002] AS Año2002, [2003] AS Año2003,[2004] AS Año2004,[2005] AS Año2005,
	[2006] AS Año2006,[2007] AS Año2007,[2008] AS Año2008,[2009] AS Año2009,[2010] AS Año2010,[2011] AS Año2011
	INTO TCREAD_PIVOT_CANTIDADALTAS
	FROM (
			SELECT YEAR(A.FH_ALTA) AÑO_ALTA,B.AREA,COUNT(A.CODIGO) CANTIDAD_ALTAS 
			FROM [dbo].[TB_CLIENTE_PERFIL] A
			INNER JOIN [dbo].[TB_UBIGEO] B
			ON A.COD_UBIGEO = B.COD_UBIGEO
			WHERE YEAR(A.FH_ALTA) >= 2000
			GROUP BY YEAR(A.FH_ALTA), B.AREA
		) T
	PIVOT
		(
		SUM(CANTIDAD_ALTAS)
		FOR
		AÑO_ALTA IN ([2000],[2001],[2002],[2003],[2004],[2005],[2006],[2007],[2008],[2009],[2010],[2011]) 
		 )AS PV
	ORDER BY AREA ASC

--Mostrando tabla Pivoteada
SELECT * FROM [dbo].[TCREAD_PIVOT_CANTIDADALTAS]

--Tabla resultante del UnPivot, regresando a la tabla inicial antes de pivotear
SELECT AÑO_ALTA, AREA, CANTIDAD_ALTAS
INTO TCREADA_UNPIVOT_CANTIDADALTAS
FROM [dbo].[TCREAD_PIVOT_CANTIDADALTAS] T
UNPIVOT
	(
		CANTIDAD_ALTAS 
		FOR AÑO_ALTA IN(Año2000,Año2001,Año2002,Año2003,Año2004,Año2005,Año2006,
						Año2007,Año2008,Año2009,Año2010,Año2011)
	) AS unpvt

--Mostrando tabla UnPivoteada
SELECT * FROM [dbo].[TCREADA_UNPIVOT_CANTIDADALTAS]