USE [BD_BANCO1]
GO

/****** Object:  Trigger [dbo].[ESTADO_CIVIL_ALERTA2]    Script Date: 25/02/2024 08:29:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[ESTADO_CIVIL_ALERTA2]
ON [dbo].[TB_ESTADO_CIVIL]
AFTER DELETE
AS
BEGIN
	PRINT('SE ELIMINARON LOS DATOS CORRECTAMENTE')
END
GO

ALTER TABLE [dbo].[TB_ESTADO_CIVIL] ENABLE TRIGGER [ESTADO_CIVIL_ALERTA2]
GO

