USE [BD_BANCO1]
GO

/****** Object:  View [dbo].[VW_CLIENTESMYINGRE]    Script Date: 25/02/2024 08:30:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_CLIENTESMYINGRE] AS
SELECT TOP(4) INGRESO,CODIGO FROM [dbo].[TB_CLIENTE_PERFIL]
ORDER BY INGRESO DESC
GO

