USE [BD_BANCO1]
GO

/****** Object:  View [dbo].[VW_DATOS]    Script Date: 25/02/2024 08:31:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_DATOS] AS
SELECT A.CODIGO,B.ZONA,A.SEXO,A.ECIVIL,C.DEPARTAMENTO, A.INGRESO 
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_AGENCIA] B
ON B.COD_AGENCIA = A.COD_AGENCIA COLLATE SQL_Latin1_General_CP1_CI_AS
INNER JOIN [dbo].[TB_UBIGEO] C
ON A.COD_UBIGEO = C.COD_UBIGEO
WHERE A.INGRESO IS NOT NULL AND A.INGRESO > 0
GO

