USE [BD_BANCO1]
GO

/****** Object:  StoredProcedure [dbo].[SP_CLIENTESHIPO_COMPA]    Script Date: 25/02/2024 08:33:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_CLIENTESHIPO_COMPA](@DEPARTAMENTO NVARCHAR(30)) AS
BEGIN

SELECT A.CODIGO,B.SALDO_REAL,B.COD_PRODUCTO,C.DEPARTAMENTO FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_CLIENTE_PRESTAMOS] B
ON A.CODIGO = B.CODIGO
INNER JOIN [dbo].[TB_UBIGEO] C
ON A.COD_UBIGEO = C.COD_UBIGEO
WHERE C.DEPARTAMENTO = @DEPARTAMENTO AND
	B.COD_PRODUCTO LIKE 'H%' AND
	B.SALDO_REAL > 500000
ORDER BY 2

END
GO

