USE [BD_BANCO1]
GO

/****** Object:  StoredProcedure [dbo].[SP_CLIENTEMLIMA]    Script Date: 25/02/2024 08:32:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_CLIENTEMLIMA] AS
BEGIN

SELECT A.CODIGO,A.SEXO,A.INGRESO,B.DEPARTAMENTO 
FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE B.DEPARTAMENTO = 'LIMA' AND
	A.SEXO = 'M' AND
	A.INGRESO > 35000
ORDER BY 3

END
GO

