USE [BD_BANCO1]
GO

/****** Object:  Table [dbo].[TCREADA_CAMPAÑARENOVACION]    Script Date: 25/02/2024 08:25:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TCREADA_CAMPAÑARENOVACION](
	[CODIGO] [varchar](12) NULL,
	[FECHA_ALTA] [varchar](10) NULL,
	[FECHA_VENCIMIENTO] [varchar](10) NULL,
	[RENOVACION_CAMPAÑA] [varchar](30) NULL
) ON [PRIMARY]
GO

