USE [BD_BANCO1]
GO

/****** Object:  Table [dbo].[TCREADA_TENECIAPRODUCTOS]    Script Date: 25/02/2024 08:25:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TCREADA_TENECIAPRODUCTOS](
	[CODIGO] [varchar](12) NULL,
	[SEGMENTO] [nvarchar](255) NULL,
	[EDAD] [numeric](17, 6) NULL,
	[INGRESO] [numeric](9, 2) NULL,
	[TENENCIA_PRODUCTOS_PASIVOS] [varchar](1) NOT NULL,
	[TENENCIA_PRODUCTOS_ACTIVOS] [varchar](1) NOT NULL
) ON [PRIMARY]
GO

