USE [BD_BANCO1]
GO

/****** Object:  Table [dbo].[TCREADA_UNPIVOT_CANTIDADALTAS]    Script Date: 25/02/2024 08:26:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TCREADA_UNPIVOT_CANTIDADALTAS](
	[AÑO_ALTA] [nvarchar](128) NULL,
	[AREA] [varchar](13) NOT NULL,
	[CANTIDAD_ALTAS] [int] NULL
) ON [PRIMARY]
GO

