USE [BD_BANCO1]
GO

/****** Object:  Table [dbo].[TCREADA_UNPIVOT_PRESTAMOS2010]    Script Date: 25/02/2024 08:26:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TCREADA_UNPIVOT_PRESTAMOS2010](
	[MES_2010] [nvarchar](128) NULL,
	[PRESTAMO] [nvarchar](255) NULL,
	[DESEMBOLSO] [numeric](38, 0) NULL
) ON [PRIMARY]
GO

