USE [BD_BANCO1]
GO

/****** Object:  UserDefinedFunction [dbo].[FN_CLIENTDESEM_COMPA]    Script Date: 25/02/2024 08:34:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[FN_CLIENTDESEM_COMPA](@PRESTAMO NVARCHAR(255)) RETURNS TABLE AS
RETURN 
(SELECT A.CODIGO, A.DESEMBOLSO,B.PRESTAMO FROM [dbo].[TB_CLIENTE_PRESTAMOS] A
INNER JOIN [dbo].[TB_TIPO_PRESTAMO] B
ON A.COD_PRODUCTO = B.COD_PRODUCTO
WHERE A.DESEMBOLSO > 2000000 AND 
B.PRESTAMO = @PRESTAMO)
GO

