USE [BD_BANCO1]
GO

/****** Object:  UserDefinedFunction [dbo].[FN_CLIENTEMYINGRE]    Script Date: 25/02/2024 08:35:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[FN_CLIENTEMYINGRE]() RETURNS TABLE AS
RETURN
(SELECT A.CODIGO,A.INGRESO,B.DEPARTAMENTO FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE B.DEPARTAMENTO = 'LIMA' AND
	A.INGRESO > 35000)
GO

