USE [BD_BANCO1]
GO

/****** Object:  UserDefinedFunction [dbo].[FN_CLIENTEMYINGRE_COMPA]    Script Date: 25/02/2024 08:35:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[FN_CLIENTEMYINGRE_COMPA](@DEPARTAMENTO NVARCHAR(30)) RETURNS TABLE AS
RETURN
(SELECT A.CODIGO,A.INGRESO,B.DEPARTAMENTO FROM [dbo].[TB_CLIENTE_PERFIL] A
INNER JOIN [dbo].[TB_UBIGEO] B
ON A.COD_UBIGEO = B.COD_UBIGEO
WHERE B.DEPARTAMENTO = @DEPARTAMENTO AND
	A.INGRESO > 35000)
GO

