USE [BD_BANCO1]
GO

/****** Object:  UserDefinedFunction [dbo].[FN_SUMADESEM]    Script Date: 25/02/2024 08:35:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[FN_SUMADESEM](@CODIGO NVARCHAR(12)) RETURNS FLOAT AS
BEGIN
	DECLARE @SUMA FLOAT
	SET @SUMA = (SELECT SUM(DESEMBOLSO) FROM [dbo].[TB_CLIENTE_PRESTAMOS]
	WHERE CODIGO = @CODIGO)
	RETURN @SUMA
END
GO

